name: 'TollGate SDK Build'
description: 'Composite action for building TollGate modules with OpenWRT SDK'

inputs:
  module-name:
    description: 'Name of the module to build'
    required: true
  module-repository:
    description: 'Repository of the module (e.g. OpenTollGate/tollgate-module-basic-go)'
    required: false
    default: ${{ github.repository }}
  package-path:
    description: 'Path to the package source within the repository (e.g. . or package/my-module)'
    required: false
    default: '.'
  device:
    description: 'Target device (e.g., gl-mt6000)'
    required: true
  target:
    description: 'OpenWRT target (e.g., mediatek)'
    required: true
  subtarget:
    description: 'OpenWRT subtarget (e.g., filogic)'
    required: true
  sdk-version:
    description: 'OpenWRT SDK version'
    required: false
    default: '23.05.3'
  blossom-server:
    description: 'Blossom server URL for upload'
    required: true
  nostr-private-key:
    description: 'Nostr private key for event signing'
    required: true

outputs:
  package-hash:
    description: 'SHA256 hash of the built package'
    value: ${{ steps.upload.outputs.hash }}
  package-url:
    description: 'Blossom URL of the uploaded package'
    value: ${{ steps.upload.outputs.url }}

runs:
  using: 'composite'
  steps:
    - name: Checkout module repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.module-repository }}
        path: module

    - name: Check for Go module
      id: check-go
      shell: bash
      run: |
        if [ -f "module/${{ inputs.package-path }}/go.sum" ]; then
          echo "has_go=true" >> $GITHUB_OUTPUT
        else
          echo "has_go=false" >> $GITHUB_OUTPUT
        fi

    # Caching Steps for Speed Optimization
    - name: Cache SDK and Feeds
      id: cache-sdk
      uses: actions/cache@v4
      with:
        path: |
          sdk
          !sdk/bin
          !sdk/build_dir
          !sdk/tmp
        # Key includes feeds.conf hash so we rebuild if dependencies change
        key: sdk-${{ inputs.sdk-version }}-${{ inputs.target }}-${{ inputs.subtarget }}-${{ hashFiles('feeds.conf') }}

    - name: Cache OpenWrt Go Downloads
      uses: actions/cache@v4
      with:
        path: sdk/dl
        key: openwrt-dl-${{ hashFiles('module/**/go.sum') }}
        restore-keys: |
          openwrt-dl-

    - name: Setup Go (conditional)
      if: steps.check-go.outputs.has_go == 'true'
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: true
        cache-dependency-path: module/${{ inputs.package-path }}/go.sum

    # SDK Download - Only runs if Cache MISS
    - name: Download OpenWRT SDK
      if: steps.cache-sdk.outputs.cache-hit != 'true'
      shell: bash
      run: |
        SDK_URL="https://downloads.openwrt.org/releases/${{ inputs.sdk-version }}/targets/${{ inputs.target }}/${{ inputs.subtarget }}/openwrt-sdk-${{ inputs.sdk-version }}-${{ inputs.target }}-${{ inputs.subtarget }}_gcc-*.Linux-x86_64.tar.xz"
        echo "Downloading SDK from: $SDK_URL"
        
        SDK_FILE=$(curl -s "https://downloads.openwrt.org/releases/${{ inputs.sdk-version }}/targets/${{ inputs.target }}/${{ inputs.subtarget }}/" | \
          grep -oP 'openwrt-sdk[^"]+Linux-x86_64\.tar\.xz' | head -1)
        
        if [ -z "$SDK_FILE" ]; then
          echo "Error: Could not find SDK file"
          exit 1
        fi
        
        wget -q "https://downloads.openwrt.org/releases/${{ inputs.sdk-version }}/targets/${{ inputs.target }}/${{ inputs.subtarget }}/$SDK_FILE"
        tar -xf "$SDK_FILE"
        rm "$SDK_FILE"
        mv openwrt-sdk-* sdk
        
        # Initial cleanup to save space
        rm -rf sdk/bin sdk/build_dir

    # Environment Setup - Runs EVERY time to ensure consistency (and fix libc issue)
    - name: Setup Custom Golang Environment & Feeds
      shell: bash
      run: |
        echo "Setting up custom environment..."
        
        # 1. Inject custom Golang package into SDK
        mkdir -p sdk/package/golang
        if [ -d "lang/golang" ]; then
          # Force overwrite to ensure we have latest version from repo
          cp -r lang/golang/* sdk/package/golang/
        else
          echo "Error: lang/golang directory not found"
          exit 1
        fi

        # 2. Copy optimized feeds.conf
        if [ -f "feeds.conf" ]; then
          cp feeds.conf sdk/feeds.conf
        fi

        # 3. Handle Feeds Update/Install
        cd sdk
        if [ "${{ steps.cache-sdk.outputs.cache-hit }}" != "true" ]; then
          echo "Cache miss: Running full feeds update..."
          ./scripts/feeds update -a
          ./scripts/feeds install -a
        else
          echo "Cache hit: Running lightweight feeds install..."
          # Re-install ensures symlinks are correct even if moved/restored
          ./scripts/feeds install -a
        fi
        cd ..
        
        # 4. Critical: Inject Makefiles for Golang Build System
        # This fixes the libc errors and ensures correct build flags
        cp golang.mk sdk/include/golang.mk
        cp lang/golang/golang-package.mk sdk/include/
        cp lang/golang/golang-values.mk sdk/include/
        cp lang/golang/golang-build.sh sdk/include/
        chmod +x sdk/include/golang-build.sh
        
        echo "Environment setup complete."

    - name: Prepare module package
      shell: bash
      run: |
        mkdir -p sdk/package/${{ inputs.module-name }}
        cp -a module/${{ inputs.package-path }}/. sdk/package/${{ inputs.module-name }}/
        
        # Create local source tarball to avoid git fetch issues in SDK
        mkdir -p sdk/dl
        tar --exclude=.git -C module/${{ inputs.package-path }} -c . | xz > sdk/dl/${{ inputs.module-name }}-local.tar.xz
        
        cd sdk/package/${{ inputs.module-name }}
        
        # Patch Makefile to use local tarball
        sed -i 's|^PKG_SOURCE_URL:=.*|PKG_SOURCE_URL:=$(TOPDIR)/dl|' Makefile
        if grep -q "PKG_SOURCE_PROTO" Makefile; then
            sed -i 's/^PKG_SOURCE_PROTO:=.*/PKG_SOURCE_PROTO:=file/' Makefile
        else
            sed -i '/^PKG_SOURCE_URL:=/a PKG_SOURCE_PROTO:=file' Makefile
        fi
        sed -i 's/^PKG_SOURCE:=.*/PKG_SOURCE:=${{ inputs.module-name }}-local.tar.xz/' Makefile
        sed -i 's/^PKG_HASH:=.*/PKG_HASH:=skip/' Makefile
        sed -i 's/^PKG_MIRROR_HASH:=.*/PKG_MIRROR_HASH:=skip/' Makefile
        sed -i 's/^PKG_SOURCE_VERSION:=.*/PKG_SOURCE_VERSION:=local/' Makefile

    - name: Build package
      shell: bash
      working-directory: sdk
      run: |
        # Configure
        make defconfig
        
        # Build - using V=w (Warnings) instead of V=s (All) to reduce log size and I/O time
        echo "Starting build..."
        make package/${{ inputs.module-name }}/compile V=w -j$(nproc) || \
        make package/${{ inputs.module-name }}/compile V=s -j1

    - name: Find built package
      id: find-package
      shell: bash
      run: |
        PACKAGE_FILE=$(find sdk/bin/packages -name "${{ inputs.module-name }}*.ipk" | head -1)
        if [ -z "$PACKAGE_FILE" ]; then
          echo "Error: Built package not found"
          exit 1
        fi
        echo "package_path=$PACKAGE_FILE" >> $GITHUB_OUTPUT
        echo "Found package: $PACKAGE_FILE"

    - name: Calculate package hash
      id: hash
      shell: bash
      run: |
        HASH=$(sha256sum ${{ steps.find-package.outputs.package_path }} | cut -d' ' -f1)
        echo "sha256=$HASH" >> $GITHUB_OUTPUT

    - name: Upload to Blossom
      id: upload
      shell: bash
      run: |
        PACKAGE_PATH="${{ steps.find-package.outputs.package_path }}"
        HASH="${{ steps.hash.outputs.sha256 }}"
        
        RESPONSE=$(curl -X PUT \
          -H "Content-Type: application/octet-stream" \
          -H "X-SHA-256: $HASH" \
          --data-binary "@$PACKAGE_PATH" \
          "${{ inputs.blossom-server }}/upload")
        
        echo "Upload response: $RESPONSE"
        URL="${{ inputs.blossom-server }}/$HASH"
        echo "url=$URL" >> $GITHUB_OUTPUT
        echo "hash=$HASH" >> $GITHUB_OUTPUT

    - name: Create Nostr announcement
      shell: bash
      run: |
        cat > event.json << EOF
        {
          "kind": 1063,
          "content": "New TollGate package: ${{ inputs.module-name }}",
          "tags": [
            ["url", "${{ steps.upload.outputs.url }}"],
            ["x", "${{ steps.upload.outputs.hash }}"],
            ["m", "application/octet-stream"],
            ["device", "${{ inputs.device }}"],
            ["target", "${{ inputs.target }}/${{ inputs.subtarget }}"]
          ]
        }
        EOF
        cat event.json
