name: 'TollGate SDK Build'
description: 'Composite action for building TollGate modules with OpenWRT SDK'

inputs:
  module-name:
    description: 'Name of the module to build'
    required: true
  module-repository:
    description: 'Repository of the module (e.g. OpenTollGate/tollgate-module-basic-go)'
    required: false
    default: ${{ github.repository }}
  package-path:
    description: 'Path to the package source within the repository (e.g. . or package/my-module)'
    required: false
    default: '.'
  device:
    description: 'Target device (e.g., gl-mt6000)'
    required: true
  target:
    description: 'OpenWRT target (e.g., mediatek)'
    required: true
  subtarget:
    description: 'OpenWRT subtarget (e.g., filogic)'
    required: true
  sdk-version:
    description: 'OpenWRT SDK version'
    required: false
    default: '23.05.3'
  blossom-server:
    description: 'Blossom server URL for upload'
    required: true
  nostr-private-key:
    description: 'Nostr private key for event signing'
    required: true

outputs:
  package-hash:
    description: 'SHA256 hash of the built package'
    value: ${{ steps.upload.outputs.hash }}
  package-url:
    description: 'Blossom URL of the uploaded package'
    value: ${{ steps.upload.outputs.url }}

runs:
  using: 'composite'
  steps:
    - name: Checkout module repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.module-repository }}
        path: module

    - name: Check for Go module
      id: check-go
      shell: bash
      run: |
        # Check inside the specific package path
        if [ -f "module/${{ inputs.package-path }}/go.sum" ]; then
          echo "has_go=true" >> $GITHUB_OUTPUT
          echo "Found go.sum - Go caching will be enabled"
        else
          echo "has_go=false" >> $GITHUB_OUTPUT
          echo "No go.sum found - skipping Go cache"
        fi

    - name: Setup Go (conditional)
      if: steps.check-go.outputs.has_go == 'true'
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: true
        # Point cache to the correct go.sum location
        cache-dependency-path: module/${{ inputs.package-path }}/go.sum

    - name: Setup Go (without cache)
      if: steps.check-go.outputs.has_go == 'false'
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: false

    - name: Download OpenWRT SDK
      shell: bash
      run: |
        SDK_URL="https://downloads.openwrt.org/releases/${{ inputs.sdk-version }}/targets/${{ inputs.target }}/${{ inputs.subtarget }}/openwrt-sdk-${{ inputs.sdk-version }}-${{ inputs.target }}-${{ inputs.subtarget }}_gcc-*.Linux-x86_64.tar.xz"
        echo "Downloading SDK from: $SDK_URL"
        
        # Find exact SDK filename
        SDK_FILE=$(curl -s "https://downloads.openwrt.org/releases/${{ inputs.sdk-version }}/targets/${{ inputs.target }}/${{ inputs.subtarget }}/" | \
          grep -oP 'openwrt-sdk[^"]+Linux-x86_64\.tar\.xz' | head -1)
        
        if [ -z "$SDK_FILE" ]; then
          echo "Error: Could not find SDK file"
          exit 1
        fi
        
        wget -q "https://downloads.openwrt.org/releases/${{ inputs.sdk-version }}/targets/${{ inputs.target }}/${{ inputs.subtarget }}/$SDK_FILE"
        tar -xf "$SDK_FILE"
        
        # Remove archive to prevent wildcard matching issues with mv
        rm "$SDK_FILE"
        
        mv openwrt-sdk-* sdk

    - name: Prepare module package
      shell: bash
      run: |
        # 1. Create package directory in SDK
        mkdir -p sdk/package/${{ inputs.module-name }}
        
        # 2. Copy the Package Definition to SDK
        # Using '/.' ensures we copy contents including hidden files, and cp -a preserves attributes
        cp -a module/${{ inputs.package-path }}/. sdk/package/${{ inputs.module-name }}/
        
        # 3. Create a local source tarball from the CHECKOUT.
        # This bypasses the need for the SDK to download from GitHub.
        mkdir -p sdk/dl
        # Create tarball of the module content (excluding .git)
        tar --exclude=.git -C module/${{ inputs.package-path }} -c . | xz > sdk/dl/${{ inputs.module-name }}-local.tar.xz
        
        # 4. Patch the Makefile in the SDK to use the local tarball
        cd sdk/package/${{ inputs.module-name }}
        
        echo "Patching Makefile to use local source..."
        
        # Change URL to local dl directory
        sed -i 's|^PKG_SOURCE_URL:=.*|PKG_SOURCE_URL:=$(TOPDIR)/dl|' Makefile
        
        # Ensure PROTO is file (replace if exists, otherwise append after URL to be safe)
        if grep -q "PKG_SOURCE_PROTO" Makefile; then
            sed -i 's/^PKG_SOURCE_PROTO:=.*/PKG_SOURCE_PROTO:=file/' Makefile
        else
            sed -i '/^PKG_SOURCE_URL:=/a PKG_SOURCE_PROTO:=file' Makefile
        fi
        
        # Change Source File Name
        sed -i 's/^PKG_SOURCE:=.*/PKG_SOURCE:=${{ inputs.module-name }}-local.tar.xz/' Makefile
        
        # Skip Hash Verification (since we just created the file)
        sed -i 's/^PKG_HASH:=.*/PKG_HASH:=skip/' Makefile
        sed -i 's/^PKG_MIRROR_HASH:=.*/PKG_MIRROR_HASH:=skip/' Makefile
        
        # Force version to 'local' to avoid git mismatch errors
        sed -i 's/^PKG_SOURCE_VERSION:=.*/PKG_SOURCE_VERSION:=local/' Makefile
        
        echo "Patched Makefile content (grep PKG_):"
        grep "PKG_" Makefile || true

    - name: Build package
      shell: bash
      working-directory: sdk
      run: |
        # Update feeds
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
        # Configure
        make defconfig
        
        # Build the package
        make package/${{ inputs.module-name }}/compile V=s -j$(nproc) || \
        make package/${{ inputs.module-name }}/compile V=s -j1

    - name: Find built package
      id: find-package
      shell: bash
      run: |
        PACKAGE_FILE=$(find sdk/bin/packages -name "${{ inputs.module-name }}*.ipk" | head -1)
        if [ -z "$PACKAGE_FILE" ]; then
          echo "Error: Built package not found"
          exit 1
        fi
        echo "package_path=$PACKAGE_FILE" >> $GITHUB_OUTPUT
        echo "Found package: $PACKAGE_FILE"

    - name: Calculate package hash
      id: hash
      shell: bash
      run: |
        HASH=$(sha256sum ${{ steps.find-package.outputs.package_path }} | cut -d' ' -f1)
        echo "sha256=$HASH" >> $GITHUB_OUTPUT
        echo "Package SHA256: $HASH"

    - name: Upload to Blossom
      id: upload
      shell: bash
      run: |
        PACKAGE_PATH="${{ steps.find-package.outputs.package_path }}"
        PACKAGE_NAME=$(basename "$PACKAGE_PATH")
        HASH="${{ steps.hash.outputs.sha256 }}"
        
        # Upload to blossom server
        RESPONSE=$(curl -X PUT \
          -H "Content-Type: application/octet-stream" \
          -H "X-SHA-256: $HASH" \
          --data-binary "@$PACKAGE_PATH" \
          "${{ inputs.blossom-server }}/upload")
        
        echo "Upload response: $RESPONSE"
        
        URL="${{ inputs.blossom-server }}/$HASH"
        echo "url=$URL" >> $GITHUB_OUTPUT
        echo "hash=$HASH" >> $GITHUB_OUTPUT

    - name: Create Nostr announcement
      shell: bash
      run: |
        # Create nostr event announcing the package
        cat > event.json << EOF
        {
          "kind": 1063,
          "content": "New TollGate package: ${{ inputs.module-name }}",
          "tags": [
            ["url", "${{ steps.upload.outputs.url }}"],
            ["x", "${{ steps.upload.outputs.hash }}"],
            ["m", "application/octet-stream"],
            ["device", "${{ inputs.device }}"],
            ["target", "${{ inputs.target }}/${{ inputs.subtarget }}"]
          ]
        }
        EOF
        
        echo "Nostr event created (signing would happen here with actual implementation)"
        cat event.json
