name: 'TollGate SDK Build'
description: 'Composite action for building TollGate modules with OpenWRT SDK'

inputs:
  module-name:
    description: 'Name of the module to build'
    required: true
  module-repository:
    description: 'Repository of the module'
    required: false
    default: ${{ github.repository }}
  package-path:
    description: 'Path to the package source'
    required: false
    default: '.'
  device:
    description: 'Target device'
    required: true
  target:
    description: 'OpenWRT target'
    required: true
  subtarget:
    description: 'OpenWRT subtarget'
    required: true
  sdk-version:
    description: 'OpenWRT SDK version'
    required: false
    default: '23.05.3'
  blossom-server:
    description: 'Blossom server URL'
    required: true
  nostr-private-key:
    description: 'Nostr private key (nsec)'
    required: true

outputs:
  package-hash:
    description: 'SHA256 hash of the built package'
    value: ${{ steps.hash.outputs.sha256 }}
  package-url:
    description: 'Blossom URL of the uploaded package'
    value: ${{ steps.upload.outputs.url }}

runs:
  using: 'composite'
  steps:
    - name: Checkout module repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.module-repository }}
        path: module

    - name: Check for Go module
      id: check-go
      shell: bash
      run: |
        if [ -f "module/${{ inputs.package-path }}/go.sum" ]; then
          echo "has_go=true" >> $GITHUB_OUTPUT
        else
          echo "has_go=false" >> $GITHUB_OUTPUT
        fi

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        check-latest: true
        cache: ${{ steps.check-go.outputs.has_go == 'true' }}
        cache-dependency-path: module/${{ inputs.package-path }}/go.sum

    - name: Prepare SDK and Environment
      shell: bash
      run: |
        function log_progress() {
          echo "::notice title=Build Progress::$1"
          echo "::group::$1"
        }
        function end_step() {
          echo "::endgroup::"
        }

        log_progress "Step 1/7: Downloading OpenWrt SDK"
        
        SDK_FILE=$(curl -s "https://downloads.openwrt.org/releases/${{ inputs.sdk-version }}/targets/${{ inputs.target }}/${{ inputs.subtarget }}/" | \
          grep -oP 'openwrt-sdk[^"]+Linux-x86_64\.tar\.xz' | head -1)
        
        if [ -z "$SDK_FILE" ]; then
          echo "::error::Could not determine SDK filename."
          exit 1
        fi
        
        wget -q "https://downloads.openwrt.org/releases/${{ inputs.sdk-version }}/targets/${{ inputs.target }}/${{ inputs.subtarget }}/$SDK_FILE"
        tar -xf "$SDK_FILE"
        rm "$SDK_FILE"
        mv openwrt-sdk-* sdk
        end_step

        log_progress "Step 2/7: Setting up build environment"
        
        mkdir -p sdk/package/golang
        if [ -d "lang/golang" ]; then
          cp -r lang/golang/* sdk/package/golang/
        else
          echo "::error::lang/golang directory not found."
          exit 1
        fi

        # Patch SDK Golang to 1.24.2
        if [ -f sdk/package/golang/golang/Makefile ]; then
            sed -i 's/^GO_VERSION_MAJOR_MINOR:=.*/GO_VERSION_MAJOR_MINOR:=1.24/' sdk/package/golang/golang/Makefile
            sed -i 's/^GO_VERSION_PATCH:=.*/GO_VERSION_PATCH:=2/' sdk/package/golang/golang/Makefile
        fi
        
        if [ -f "feeds.conf" ]; then
          cp feeds.conf sdk/feeds.conf
        fi

        # Ensure base feed exists (needed for lua headers) and use GitHub Mirrors
        if ! grep -q "src-git base" sdk/feeds.conf && ! grep -q "src-git-full base" sdk/feeds.conf; then
             echo "src-git base https://github.com/openwrt/openwrt.git;openwrt-23.05" >> sdk/feeds.conf
        fi
        sed -i 's|git.openwrt.org/openwrt/openwrt.git|github.com/openwrt/openwrt.git|g' sdk/feeds.conf
        sed -i 's|git.openwrt.org/feed/packages.git|github.com/openwrt/packages.git|g' sdk/feeds.conf
        sed -i 's|git.openwrt.org/project/luci.git|github.com/openwrt/luci.git|g' sdk/feeds.conf
        sed -i 's|git.openwrt.org/feed/routing.git|github.com/openwrt/routing.git|g' sdk/feeds.conf
        sed -i 's|git.openwrt.org/feed/telephony.git|github.com/openwrt/telephony.git|g' sdk/feeds.conf
        
        cp golang.mk sdk/include/golang.mk
        cp lang/golang/golang-package.mk sdk/include/
        cp lang/golang/golang-values.mk sdk/include/
        cp lang/golang/golang-build.sh sdk/include/
        chmod +x sdk/include/golang-build.sh
        end_step

        log_progress "Step 3/7: Preparing package sources"
        
        mkdir -p sdk/package/${{ inputs.module-name }}
        cp -a module/${{ inputs.package-path }}/. sdk/package/${{ inputs.module-name }}/
        
        mkdir -p sdk/dl
        tar --exclude=.git -C module/${{ inputs.package-path }} -c . | xz > sdk/dl/${{ inputs.module-name }}-local.tar.xz
        
        # --- CRITICAL MAKEFILE PATCHING ---
        cd sdk/package/${{ inputs.module-name }}
        
        sed -i 's|^PKG_SOURCE_URL:=.*|PKG_SOURCE_URL:=$(TOPDIR)/dl|' Makefile
        if grep -q "PKG_SOURCE_PROTO" Makefile; then
            sed -i 's/^PKG_SOURCE_PROTO:=.*/PKG_SOURCE_PROTO:=file/' Makefile
        else
            sed -i '/^PKG_SOURCE_URL:=/a PKG_SOURCE_PROTO:=file' Makefile
        fi
        sed -i 's/^PKG_SOURCE:=.*/PKG_SOURCE:=${{ inputs.module-name }}-local.tar.xz/' Makefile
        sed -i 's/^PKG_HASH:=.*/PKG_HASH:=skip/' Makefile
        sed -i 's/^PKG_MIRROR_HASH:=.*/PKG_MIRROR_HASH:=skip/' Makefile
        sed -i 's/^PKG_SOURCE_VERSION:=.*/PKG_SOURCE_VERSION:=local/' Makefile
        
        # Ensure PACKAGE NAME matches INPUT name
        sed -i 's/^PKG_NAME:=.*/PKG_NAME:=${{ inputs.module-name }}/' Makefile
        
        # Inject golang-package.mk if missing
        if ! grep -q "golang-package.mk" Makefile; then
           sed -i '/include $(TOPDIR)\/rules.mk/a include $(INCLUDE_DIR)/golang-package.mk' Makefile
        fi

        # Patch 'go build' to use cross-compile vars
        if grep -q "go build" Makefile; then
           sed -i 's/\tgo build/\t$(GO_PKG_TARGET_VARS) go build/g' Makefile
           sed -i 's/ go build/ $(GO_PKG_TARGET_VARS) go build/g' Makefile
        fi
        
        cat Makefile
        cd ../../..
        end_step

    - name: Update Feeds
      shell: bash
      working-directory: sdk
      run: |
        echo "::notice title=Build Progress::Step 4/7: Updating Feeds..."
        echo "::group::Feed Logs"
        n=0
        until [ "$n" -ge 5 ]; do
           ./scripts/feeds update -a && break
           n=$((n+1))
           sleep 5
        done
        
        ./scripts/feeds install -f -p custom golang
        ./scripts/feeds install -a
        echo "::endgroup::"

    - name: Compile Package
      shell: bash
      working-directory: sdk
      run: |
        echo "::notice title=Build Progress::Step 5/7: Compiling ${{ inputs.module-name }}..."
        echo "::group::Compile Logs"
        make defconfig
        make package/${{ inputs.module-name }}/compile V=s -j$(nproc) || make package/${{ inputs.module-name }}/compile V=s -j1
        echo "::endgroup::"

    - name: Process Artifacts
      id: find-package
      shell: bash
      run: |
        echo "::notice title=Build Progress::Step 6/7: Processing Artifacts..."
        
        # Safe find command (avoids broken pipe error)
        PACKAGE_FILE=$(find sdk/bin/packages -type f -name "${{ inputs.module-name }}*.ipk" -print -quit)
        
        if [ -z "$PACKAGE_FILE" ]; then
          echo "::error::Build failed: No .ipk file found!"
          exit 1
        fi
        
        echo "package_path=$PACKAGE_FILE" >> $GITHUB_OUTPUT

    - name: Upload Artifact to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.module-name }}-ipk
        path: ${{ steps.find-package.outputs.package_path }}
        if-no-files-found: error

    - name: Calculate Hash
      id: hash
      shell: bash
      run: |
        HASH=$(sha256sum ${{ steps.find-package.outputs.package_path }} | cut -d' ' -f1)
        echo "sha256=$HASH" >> $GITHUB_OUTPUT

    - name: Upload to Blossom
      id: upload
      uses: c03rad0r/cli-blossom-uploader-go@main
      with:
        host: ${{ inputs.blossom-server }}
        filePath: ${{ steps.find-package.outputs.package_path }}
        # WICHTIG: Das muss im Workflow übergeben werden!
        nostrPrivateKey: ${{ inputs.nostr-private-key }}

    - name: Create Nostr announcement
      shell: bash
      run: |
        echo "::notice title=Build Progress::Step 7/7: Success!"
        cat > event.json << EOF
        {
          "kind": 1063,
          "content": "New TollGate package: ${{ inputs.module-name }}",
          "tags": [
            ["url", "${{ steps.upload.outputs.url }}"],
            ["x", "${{ steps.hash.outputs.sha256 }}"],
            ["m", "application/octet-stream"],
            ["device", "${{ inputs.device }}"],
            ["target", "${{ inputs.target }}/${{ inputs.subtarget }}"]
          ]
        }
        EOF
        cat event.json
