name: 'TollGate SDK Build'
description: 'Composite action for building TollGate modules with OpenWRT SDK'

inputs:
  module-name:
    description: 'Name of the module to build'
    required: true
  module-repository:
    description: 'Repository of the module (e.g. OpenTollGate/tollgate-module-basic-go)'
    required: false
    default: ${{ github.repository }}
  package-path:
    description: 'Path to the package source within the repository (e.g. . or package/my-module)'
    required: false
    default: '.'
  device:
    description: 'Target device (e.g., gl-mt6000)'
    required: true
  target:
    description: 'OpenWRT target (e.g., mediatek)'
    required: true
  subtarget:
    description: 'OpenWRT subtarget (e.g., filogic)'
    required: true
  sdk-version:
    description: 'OpenWRT SDK version'
    required: false
    default: '23.05.3'
  blossom-server:
    description: 'Blossom server URL for upload'
    required: true
  nostr-private-key:
    description: 'Nostr private key for event signing'
    required: true

outputs:
  package-hash:
    description: 'SHA256 hash of the built package'
    value: ${{ steps.upload.outputs.hash }}
  package-url:
    description: 'Blossom URL of the uploaded package'
    value: ${{ steps.upload.outputs.url }}

runs:
  using: 'composite'
  steps:
    - name: Checkout module repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.module-repository }}
        path: module

    - name: Check for Go module
      id: check-go
      shell: bash
      run: |
        if [ -f "module/${{ inputs.package-path }}/go.sum" ]; then
          echo "has_go=true" >> $GITHUB_OUTPUT
          echo "Found go.sum - Go caching will be enabled"
        else
          echo "has_go=false" >> $GITHUB_OUTPUT
          echo "No go.sum found - skipping Go cache"
        fi

    - name: Setup Go (conditional)
      if: steps.check-go.outputs.has_go == 'true'
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: true
        cache-dependency-path: module/${{ inputs.package-path }}/go.sum

    - name: Setup Go (without cache)
      if: steps.check-go.outputs.has_go == 'false'
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: false

    - name: Download OpenWRT SDK
      shell: bash
      run: |
        SDK_URL="https://downloads.openwrt.org/releases/${{ inputs.sdk-version }}/targets/${{ inputs.target }}/${{ inputs.subtarget }}/openwrt-sdk-${{ inputs.sdk-version }}-${{ inputs.target }}-${{ inputs.subtarget }}_gcc-*.Linux-x86_64.tar.xz"
        echo "Downloading SDK from: $SDK_URL"
        
        SDK_FILE=$(curl -s "https://downloads.openwrt.org/releases/${{ inputs.sdk-version }}/targets/${{ inputs.target }}/${{ inputs.subtarget }}/" | \
          grep -oP 'openwrt-sdk[^"]+Linux-x86_64\.tar\.xz' | head -1)
        
        if [ -z "$SDK_FILE" ]; then
          echo "Error: Could not find SDK file"
          exit 1
        fi
        
        wget -q "https://downloads.openwrt.org/releases/${{ inputs.sdk-version }}/targets/${{ inputs.target }}/${{ inputs.subtarget }}/$SDK_FILE"
        tar -xf "$SDK_FILE"
        rm "$SDK_FILE"
        mv openwrt-sdk-* sdk

    - name: Setup Custom Build Environment
      shell: bash
      run: |
        echo "Setting up custom environment..."
        
        mkdir -p sdk/package/golang
        if [ -d "lang/golang" ]; then
          cp -r lang/golang/* sdk/package/golang/
        else
          echo "Error: lang/golang directory not found"
          exit 1
        fi
        
        if [ -f "feeds.conf" ]; then
          cp feeds.conf sdk/feeds.conf
        fi

        # FIX: Ensure base feed exists and rewrite to GitHub mirrors
        if ! grep -q "src-git base" sdk/feeds.conf && ! grep -q "src-git-full base" sdk/feeds.conf; then
             echo "Adding missing base feed..."
             echo "src-git base https://github.com/openwrt/openwrt.git;openwrt-23.05" >> sdk/feeds.conf
        fi
        sed -i 's|git.openwrt.org/openwrt/openwrt.git|github.com/openwrt/openwrt.git|g' sdk/feeds.conf
        sed -i 's|git.openwrt.org/feed/packages.git|github.com/openwrt/packages.git|g' sdk/feeds.conf
        sed -i 's|git.openwrt.org/project/luci.git|github.com/openwrt/luci.git|g' sdk/feeds.conf
        sed -i 's|git.openwrt.org/feed/routing.git|github.com/openwrt/routing.git|g' sdk/feeds.conf
        sed -i 's|git.openwrt.org/feed/telephony.git|github.com/openwrt/telephony.git|g' sdk/feeds.conf
        
        # Inject Golang Makefiles
        cp golang.mk sdk/include/golang.mk
        cp lang/golang/golang-package.mk sdk/include/
        cp lang/golang/golang-values.mk sdk/include/
        cp lang/golang/golang-build.sh sdk/include/
        chmod +x sdk/include/golang-build.sh

    - name: Prepare module package
      shell: bash
      run: |
        mkdir -p sdk/package/${{ inputs.module-name }}
        cp -a module/${{ inputs.package-path }}/. sdk/package/${{ inputs.module-name }}/
        
        mkdir -p sdk/dl
        tar --exclude=.git -C module/${{ inputs.package-path }} -c . | xz > sdk/dl/${{ inputs.module-name }}-local.tar.xz
        
        cd sdk/package/${{ inputs.module-name }}
        
        # 1. Standard Makefile patching for Source URL
        sed -i 's|^PKG_SOURCE_URL:=.*|PKG_SOURCE_URL:=$(TOPDIR)/dl|' Makefile
        if grep -q "PKG_SOURCE_PROTO" Makefile; then
            sed -i 's/^PKG_SOURCE_PROTO:=.*/PKG_SOURCE_PROTO:=file/' Makefile
        else
            sed -i '/^PKG_SOURCE_URL:=/a PKG_SOURCE_PROTO:=file' Makefile
        fi
        sed -i 's/^PKG_SOURCE:=.*/PKG_SOURCE:=${{ inputs.module-name }}-local.tar.xz/' Makefile
        sed -i 's/^PKG_HASH:=.*/PKG_HASH:=skip/' Makefile
        sed -i 's/^PKG_MIRROR_HASH:=.*/PKG_MIRROR_HASH:=skip/' Makefile
        sed -i 's/^PKG_SOURCE_VERSION:=.*/PKG_SOURCE_VERSION:=local/' Makefile
        
        # 2. CRITICAL FIX: Ensure golang-package.mk is included
        # This provides the $(GO_PKG_TARGET_VARS) variable needed for cross-compilation
        if ! grep -q "golang-package.mk" Makefile; then
           echo "Injecting golang-package.mk include..."
           sed -i '/include $(INCLUDE_DIR)\/package.mk/a include $(INCLUDE_DIR)/golang-package.mk' Makefile
        fi

        # 3. CRITICAL FIX: Patch 'go build' to use cross-compiler variables
        # Matches 'go build' preceded by tab or space and inserts the variable
        if grep -q "go build" Makefile; then
           echo "Patching Makefile to enable cross-compilation..."
           # Replace tab+go build
           sed -i 's/\tgo build/\t$(GO_PKG_TARGET_VARS) go build/g' Makefile
           # Replace space+go build (just in case)
           sed -i 's/ go build/ $(GO_PKG_TARGET_VARS) go build/g' Makefile
        fi
        
        echo "::group::Patched Makefile content"
        cat Makefile
        echo "::endgroup::"

    - name: Build package
      shell: bash
      working-directory: sdk
      run: |
        echo "Updating feeds..."
        n=0
        until [ "$n" -ge 5 ]
        do
           ./scripts/feeds update -a && break
           n=$((n+1)) 
           echo "Feed update failed (attempt $n/5). Retrying in 10 seconds..."
           sleep 10
        done
        
        if [ ! -d "feeds/luci" ] || [ ! -d "feeds/packages" ]; then
           echo "CRITICAL ERROR: Feeds failed to download."
           exit 1
        fi
        
        ./scripts/feeds install -f -p custom golang
        ./scripts/feeds install -a
        
        make defconfig
        
        # Build the package
        make package/${{ inputs.module-name }}/compile V=s -j$(nproc) || \
        make package/${{ inputs.module-name }}/compile V=s -j1

    - name: Find built package
      id: find-package
      shell: bash
      run: |
        PACKAGE_FILE=$(find sdk/bin/packages -name "${{ inputs.module-name }}*.ipk" | head -1)
        if [ -z "$PACKAGE_FILE" ]; then
          echo "Error: Built package not found"
          exit 1
        fi
        echo "package_path=$PACKAGE_FILE" >> $GITHUB_OUTPUT
        echo "Found package: $PACKAGE_FILE"

    - name: Calculate package hash
      id: hash
      shell: bash
      run: |
        HASH=$(sha256sum ${{ steps.find-package.outputs.package_path }} | cut -d' ' -f1)
        echo "sha256=$HASH" >> $GITHUB_OUTPUT
        echo "Package SHA256: $HASH"

    - name: Upload to Blossom
      id: upload
      shell: bash
      run: |
        PACKAGE_PATH="${{ steps.find-package.outputs.package_path }}"
        HASH="${{ steps.hash.outputs.sha256 }}"
        
        RESPONSE=$(curl -X PUT \
          -H "Content-Type: application/octet-stream" \
          -H "X-SHA-256: $HASH" \
          --data-binary "@$PACKAGE_PATH" \
          "${{ inputs.blossom-server }}/upload")
        
        echo "Upload response: $RESPONSE"
        
        URL="${{ inputs.blossom-server }}/$HASH"
        echo "url=$URL" >> $GITHUB_OUTPUT
        echo "hash=$HASH" >> $GITHUB_OUTPUT

    - name: Create Nostr announcement
      shell: bash
      run: |
        cat > event.json << EOF
        {
          "kind": 1063,
          "content": "New TollGate package: ${{ inputs.module-name }}",
          "tags": [
            ["url", "${{ steps.upload.outputs.url }}"],
            ["x", "${{ steps.upload.outputs.hash }}"],
            ["m", "application/octet-stream"],
            ["device", "${{ inputs.device }}"],
            ["target", "${{ inputs.target }}/${{ inputs.subtarget }}"]
          ]
        }
        EOF
        cat event.json
